### ISSUE TITLE
AttributeError: 'module' object has no attribute 'message_from_bytes'

### ISSUE THREAD

**Issue by febrez** [Phyks/Emails_SMS_Free_Mobile_API#2]
Trying to run the script after I've installed pip, requests and others but i have this error :

```
Connecting to *****… Connected
Logging as ******… Logged in
Traceback (most recent call last):
  File "emails_sms_free.py", line 154, in <module>
    hashlib.md5((imap_server['server']+imap_server['login']).encode('utf-8')).hexdigest()))
  File "emails_sms_free.py", line 98, in get_emails
    msg_parsed = email.message_from_bytes(msg_data[0][1])
AttributeError: 'module' object has no attribute 'message_from_bytes'

```

What is missing ?

Thx

**Comment by Phyks** [comment]
https://docs.python.org/3/library/email.parser.html#email.message_from_bytes has been added in Python 3.2/3.3. I guess you are running it with Python2.7 or older?

**Comment by febrez** [comment]
I have both intalled, I run it with python 2.7

**Comment by Phyks** [comment]
This script is Python 3.3+ only. I will add a note in the README.

**Comment by febrez** [comment]
Works fine with Python 3.3.5, thank you.
